ДЗ 2
twiblek/2020-2-Atom-QA-Python-V-Kuznetsov pull request #2
Opened 2020-10-16 18:15 UTC by twiblek

# Домашнее задание №2: UI

Прошу @SK1995 проверить его.

Что было сделано:
Написаны UI тесты для портала https://target.my.com/

Есть проблема с созданием кампании:
для любого типа кампании необходимо изображение/баннер. По идее, сохранено изображение в библиотеке аккаунта. И все что нужно, перетащить его dragAndDrop на место баннера. И я вижу как в браузере элемент изображения подсвечивается, как при DragAndDrop, но на место оно не ставится.
![Безымянный](https://user-images.githubusercontent.com/38328728/96293817-08435780-0ff4-11eb-952f-953ab3edbd76.png)

2020-10-21 19:29 UTC, twiblek commented
Подправил, работает.

2020-11-19 05:36 UTC, SK1995 requested changes
Спасибо, хорошая работа!
Нет селеноида (параметр --selenoid='<host:port>') и пара небольших комментариев, в остальном все ок.
Будет здорово, если поправишь.
Можно и не исправлять, но тогда балл за дз будет немного ниже.

2020-11-19 05:36 UTC, SK1995 commented on HW2/code/tests/test_basic.py
> +        image_path = path.abspath('resources/banner.jpg')
Здесь путь до изображения рассчитывается с закладкой на то, что тесты запущены из каталога `HW2/code`.
Лучше на это не закладываться и считать его относительно текущего файла, тогда независимо от того, из какой папки тесты запустились, они тут не сломаются:
```python
        import pathlib
        cur_dir_path = pathlib.Path(__file__).parent
        image_path = str(cur_dir_path.parent.resolve() / 'resources' / 'banner.jpg')
```

Сейчас просто если тесты из каталога `HW2` запустить, то в этом месте путь вычисляется неправильно.

2020-11-19 05:36 UTC, SK1995 commented on HW2/code/tests/test_basic.py
> +import allure
Тут кажется много лишних импортов

2020-11-21 13:39 UTC, twiblek commented
Исправил замечения

2020-12-01 12:52 UTC, SK1995 approved these changes

2020-12-01 12:52 UTC, SK1995 commented
Спасибо!
Поставил максимум (12 баллов).

2020-12-01 12:53 UTC, merged