ДЗ 3
twiblek/2020-2-Atom-QA-Python-V-Kuznetsov pull request #3
Opened 2020-10-18 17:40 UTC by twiblek

# Домашнее задание №3: API

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
     * Написать клиента, который будет иметь возможность авторизовываться (4 балла)
     * Написать тест на создание сегмента через API и проверку что сегмент создан (1 балл)
     * Написать тест на удаление сегмента через API (1 балл)

2020-10-20 11:13 UTC, snicks92 requested changes
Простенько, зато вроде работает. Давай чутка причешем по комменту ниже и зачту работу

2020-10-20 11:13 UTC, snicks92 commented on HW3/code/api/target_client.py
> +		}
кажется это можно куда то вынести, а то повторяется много раз

2020-10-20 17:59 UTC, twiblek commented on HW3/code/api/target_client.py
> +		}
Вынес в саму функцию запроса

2020-10-21 10:19 UTC, snicks92 approved these changes
Принято, спасибо

2020-10-21 10:19 UTC, merged